language: python
before_install:
        - python -m pip install --upgrade pip
      env: python Procfile
install:
  - pip install -r requirements.txt
script: python3 tests/test_dice.py || python tests/test_dice.py
