language: python
services:
  - docker
before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login -u "$HEROKU_USERNAME" --password=$(heroku auth:token) registry.heroku.com
install:
- pip install -r requirements.txt
jobs:
  include:
  - stage: unit tests
    script: python -m pytest -v tests/test_dice.py
  - stage: deploy to staging
    script: skip
    deploy:
      api_key: "$HEROKU_AUTH_TOKEN"
      provider: script
      script:
          # push to dockerhub & heroku
          docker push $DOCKER_USERNAME/$HEROKU_APP_NAME
          docker push registry.heroku.com/$HEROKU_APP_NAME/web
          heroku container:release web --app $HEROKU_APP_NAME
      on:
        branch: main
notifications:
  slack:
    secure: F0Lp7peA3VpI/fU9pIxoXjP6ZNRq3ksQ05qeJzRQ1vL4cMDEUkoDa/vlZmwQzZ5XJlPAZjjQRBV3qATzGaufaY3OQSzqcMq/1ZdE+Wv6qVOry1d94ptFhzWgpvCqq0WwKeHKgYGaetzaIhtDu5D7LC3iNHqdAnBk4lgApK/9OZjYVSe3TZA5hHG+P+Kym+MLqI2dv3SfTAov8WAMlILkD3nrL1vOX1TJ/QX8sSeph/MLOKs/YX8+GBg3uxBmhMgm905y3khLH9nrfTHkHBlj85Rx1BhJlf5LOWmyL9DJTxAhsl4nHBLqeDUS3/qin8Sgv9INaZyELiP2+gQ2yqBMrkX1ZZDkhJXaMCdE/lilUPj0UDW9Mo5IKsdLLaibtVR3OXXD1rpNs3g/OOGf1b6wesGHmHVW9mc5rY0NNlDk/LsA+u1ARNEsT25YuFEffQaam2+RjFWCCG4PS9yNOxUCpmfOEya9qL5yXBmNIHOvCBV8IM+Pr6A9gpghNv6RxBmoGyzvIIVcDfL8XnCpgLSF4jK67HmfO0Xoh4Xz5RCoW6dWWyj4CxqN/rRVVRoMFISXESG2giS9SzXnWA8eAbZaTse/ZZArjJhcdTVRVEg53GO0LumE//5fbY+ruxreOJssvlAZE6dTwHO9afNSuMRkNE8nHRm0y3gz/NItwPhFUK8=
