language: python
install:
- pip install -r requirements.txt
jobs:
  include:
    - stage: unit tests
      script: python -m pytest -v tests/test_dice.py
    - stage: deploy to staging
      deploy: &heroku
        provider: heroku
        app: on-demand-staging  
        api_key: $HEROKU_AUTH_TOKEN
        on:
          branch: main
    - stage: test staging
      script: 'curl http://on-demand-staging.herokuapp.com'
    - stage: deploy to production
      deploy:
        <<: *heroku
        app: on-demand-prod
    - stage: test production
      script: 'curl http://on-demand-prod.herokuapp.com'